// <auto-generated />
namespace EFMigrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AddedName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedName));
        
        string IMigrationMetadata.Id
        {
            get { return "201911200811121_Added Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
